/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_SMS.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "Clock_PWM.h"
#include "LED_CONTROL.h"
#include "I2C_Slave.h"
#include "I2C_Slave_I2C.h"
#include "I2C_Slave_PINS.h"
#include "I2C_Slave_I2C_PVT.h"
#include "I2C_Slave_PVT.h"
#include "I2C_Slave_BOOT.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "LED2.h"
#include "LED2_aliases.h"
#include "LED3.h"
#include "LED3_aliases.h"
#include "LED4.h"
#include "LED4_aliases.h"
#include "LED5.h"
#include "LED5_aliases.h"
#include "InterPin.h"
#include "InterPin_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "LED6.h"
#include "LED6_aliases.h"
#include "LED7.h"
#include "LED7_aliases.h"
#include "CapSense_SampleClk.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "I2C_Slave_SCBCLK.h"
#include "I2C_Slave_sda.h"
#include "I2C_Slave_sda_aliases.h"
#include "I2C_Slave_scl.h"
#include "I2C_Slave_scl_aliases.h"
#include "I2C_Slave_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

